// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoaoi1yf-oWCS4NKXT0Jw6AqLnEZSUzws',
    appId: '1:393610415800:web:49b1add906474b925bae4d',
    messagingSenderId: '393610415800',
    projectId: 'serene-sense2426',
    authDomain: 'serene-sense2426.firebaseapp.com',
    storageBucket: 'serene-sense2426.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_LCy_jVWjJEBAG8F4HDpziaAADxwH9u0',
    appId: '1:393610415800:android:7d34b99ff18cd5145bae4d',
    messagingSenderId: '393610415800',
    projectId: 'serene-sense2426',
    storageBucket: 'serene-sense2426.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbYQvIrBC3a2DMc64xa-LJvFUaC-HrXdI',
    appId: '1:393610415800:ios:adee3c7a1311cc8e5bae4d',
    messagingSenderId: '393610415800',
    projectId: 'serene-sense2426',
    storageBucket: 'serene-sense2426.firebasestorage.app',
    iosBundleId: 'com.example.sereneSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbYQvIrBC3a2DMc64xa-LJvFUaC-HrXdI',
    appId: '1:393610415800:ios:adee3c7a1311cc8e5bae4d',
    messagingSenderId: '393610415800',
    projectId: 'serene-sense2426',
    storageBucket: 'serene-sense2426.firebasestorage.app',
    iosBundleId: 'com.example.sereneSense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoaoi1yf-oWCS4NKXT0Jw6AqLnEZSUzws',
    appId: '1:393610415800:web:d53240413308d2255bae4d',
    messagingSenderId: '393610415800',
    projectId: 'serene-sense2426',
    authDomain: 'serene-sense2426.firebaseapp.com',
    storageBucket: 'serene-sense2426.firebasestorage.app',
  );
}
