// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRanC1YA3xD1X3-neVXPm7wePn-wZW17k',
    appId: '1:1068917620471:web:4ddfbda015104a4583ddf2',
    messagingSenderId: '1068917620471',
    projectId: 'serene-sense-chatbot',
    authDomain: 'serene-sense-chatbot.firebaseapp.com',
    storageBucket: 'serene-sense-chatbot.firebasestorage.app',
    measurementId: 'G-WFGJ38FJ3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs3a4FxopGqULEDcwZpbnja15s0RxHj9E',
    appId: '1:1068917620471:android:5370c6b1d21c351583ddf2',
    messagingSenderId: '1068917620471',
    projectId: 'serene-sense-chatbot',
    storageBucket: 'serene-sense-chatbot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX6YaDdPWKic_rp93vz3RFk8z7G88CW4w',
    appId: '1:1068917620471:ios:8e219b893275ebaa83ddf2',
    messagingSenderId: '1068917620471',
    projectId: 'serene-sense-chatbot',
    storageBucket: 'serene-sense-chatbot.firebasestorage.app',
    iosBundleId: 'com.example.sereneSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX6YaDdPWKic_rp93vz3RFk8z7G88CW4w',
    appId: '1:1068917620471:ios:8e219b893275ebaa83ddf2',
    messagingSenderId: '1068917620471',
    projectId: 'serene-sense-chatbot',
    storageBucket: 'serene-sense-chatbot.firebasestorage.app',
    iosBundleId: 'com.example.sereneSense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRanC1YA3xD1X3-neVXPm7wePn-wZW17k',
    appId: '1:1068917620471:web:6527c28825dfd85883ddf2',
    messagingSenderId: '1068917620471',
    projectId: 'serene-sense-chatbot',
    authDomain: 'serene-sense-chatbot.firebaseapp.com',
    storageBucket: 'serene-sense-chatbot.firebasestorage.app',
    measurementId: 'G-DZRKJ60KZM',
  );
}
